// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1234.MyRobot;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Gyro driveTrainGyro;
    public static SpeedController driveTrainSpeedControllerBackLeft;
    public static SpeedController driveTrainSpeedControllerBackRight;
    public static SpeedController driveTrainSpeedControllerFrontLeft;
    public static SpeedController driveTrainSpeedControllerFrontRight;
    public static RobotDrive driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainGyro = new Gyro(0);
        LiveWindow.addSensor("Drive Train", "Gyro", driveTrainGyro);
        driveTrainGyro.setSensitivity(0.007);
        driveTrainSpeedControllerBackLeft = new Talon(2);
        LiveWindow.addActuator("Drive Train", "Speed Controller Back Left", (Talon) driveTrainSpeedControllerBackLeft);
        
        driveTrainSpeedControllerBackRight = new Talon(3);
        LiveWindow.addActuator("Drive Train", "Speed Controller Back Right", (Talon) driveTrainSpeedControllerBackRight);
        
        driveTrainSpeedControllerFrontLeft = new Talon(5);
        LiveWindow.addActuator("Drive Train", "Speed Controller Front Left", (Talon) driveTrainSpeedControllerFrontLeft);
        
        driveTrainSpeedControllerFrontRight = new Talon(4);
        LiveWindow.addActuator("Drive Train", "Speed Controller Front Right", (Talon) driveTrainSpeedControllerFrontRight);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainSpeedControllerFrontLeft, driveTrainSpeedControllerBackLeft,
              driveTrainSpeedControllerFrontRight, driveTrainSpeedControllerBackRight);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
