// Generated with RobotBuilder version 0.0.1
package org.usfirst.frc2876.Robot2013.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2876.Robot2013.Robot;
/**
 *
 */
public class  AdjustShooterAngle extends Command {
    
    
    double volts = 0.0;
    public AdjustShooterAngle(double v) {

        Robot.angleShooter.potInit();
        requires(Robot.angleShooter);
        volts = v;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.angleShooter.setPotSetpoint(volts);
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return Robot.angleShooter.lmtest() || Robot.angleShooter.isFinishedAdjustingShooter();
        
        //return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.angleShooter.endShooterPID();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
